name = "cprice-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
CORS_ORIGIN = "http://localhost:3000,https://cprice.pages.dev,http://192.168.1.5:3000,https://cprice.pgs-log.cn"

# 生产环境密钥（需要通过wrangler secret命令设置）
# wrangler secret put JWT_SECRET

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cprice-db"
database_id = "579d5345-563e-42c2-b3d4-ea442daac58e"

# 开发环境配置
[env.development]
name = "cprice-api-dev"
vars = { CORS_ORIGIN = "http://localhost:3000,https://cprice.pgs-log.cn" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "cprice-db-dev"
database_id = "9a8f1cea-083f-4cd7-910f-36e9b3306a85"

# 自定义域名配置
[[env.development.routes]]
pattern = "cprice-api-dev.20990909.xyz"
custom_domain = true

# 主生产环境自定义域名配置（直接在主配置中）
[[routes]]
pattern = "cprice-api.20990909.xyz"
custom_domain = true
