name = "cprice-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
CORS_ORIGIN = "http://localhost:3000,https://cprice.pages.dev"

# 生产环境密钥（需要通过wrangler secret命令设置）
# wrangler secret put JWT_SECRET

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cprice-db"
database_id = "your-database-id-here"

# 开发环境配置
[env.development]
name = "cprice-api-dev"

[env.development.vars]
CORS_ORIGIN = "http://localhost:3000"

[[env.development.d1_databases]]
binding = "DB"
database_name = "cprice-db-dev"
database_id = "your-dev-database-id-here"

# 生产环境配置
[env.production]
name = "cprice-api"

[env.production.vars]
CORS_ORIGIN = "https://cprice.pages.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cprice-db"
database_id = "your-prod-database-id-here"
